version: '3.3'
services:
  postgres:
    container_name: syncvr-pg
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - PG_TRUST_LOCALNET=true
    ports:
      - '5432:5432'
    volumes:
      - '/volumes/postgres:/var/lib/postgresql/data'
    image: postgres
  api:
    container_name: syncvr
    ports:
      - '3333:3333'
    expose:
      - 3333
